var header="";
header += "<div class=\"headers-container\">";
header += "	<div class=\"search-section\">";
header += "		<div class=\"g-container g-clearfix\">";
header += "			<div class=\"row\">";
header += "				<a class=\"close-btn ion-close-round\"><\/a>";
header += "			    <div class=\"col-2of3\">";
header += "			    	<p>Popular pages<\/p>";
header += "			        <a class=\"g-btn-3 g-btn-sm\">Directory<\/a>";
header += "			        <a class=\"g-btn-3 g-btn-sm\">Financial Aid<\/a>";
header += "			        <a class=\"g-btn-3 g-btn-sm\">Campus Directory<\/a>";
header += "			        <a class=\"g-btn-3 g-btn-sm\">Campus Tour<\/a>";
header += "			    <\/div>";
header += "			    <div class=\"col-1of3 sm-1of2\">";
header += "			        <p>What can we help you find?<\/p>";
header += "		        	<form>";
header += "				        <div class=\"g-hidden-labels\">";
header += "			                <label for=\"searchInput\">Search SAIT:<\/label>";
header += "			                <input type=\"text\" class=\"g-form-control\" id=\"searchInput\" name=\"searchInput\" placeholder=\"Search SAIT\">";
header += "			            <\/div>";
header += "		            <\/form>";
header += "			    <\/div>";
header += "		    <\/div>";
header += "		<\/div>";
header += "	<\/div>";
header += "	<div class=\"recently-viewed\">";
header += "		<div class=\"g-container g-clearfix\">";
header += "			<div class=\"row\">";
header += "				<a class=\"close-btn ion-close-round\"><\/a>";
header += "			    <div class=\"col-1of1\">";
header += "			    	<p>7 Recently Viewed Programs <a class=\"g-btn-4 g-btn-sm g-pull-right\"><span class=\"g-icon-left ion-android-download\"><\/span>Download PDF<\/a><\/p>";
header += "			    	<div class=\"g-group g-check\">";
header += "					    <a href=\"applied-business-administration\" class=\"g-btn-3 g-btn-sm\">Bachelor of Applied Business Administration<\/a>";
header += "					    <a class=\"g-btn-3 g-btn-sm toggleCheck\"><span class=\"ion-android-cancel\"><\/span><\/a>";
header += "					<\/div>";
header += "					<div class=\"g-group g-check\">";
header += "					    <a class=\"g-btn-3 g-btn-sm\">Business Administration<\/a>";
header += "					    <a class=\"g-btn-3 g-btn-sm toggleCheck\"><span class=\"ion-android-cancel\"><\/span><\/a>";
header += "					<\/div>";
header += "					<div class=\"g-group g-check\">";
header += "					    <a class=\"g-btn-3 g-btn-sm\">Bachelor of Science Construction Project Management<\/a>";
header += "					    <a class=\"g-btn-3 g-btn-sm toggleCheck\"><span class=\"ion-android-cancel\"><\/span><\/a>";
header += "					<\/div>";
header += "					<div class=\"g-group g-check\">";
header += "					    <a class=\"g-btn-3 g-btn-sm\">Civil Engineering Technology<\/a>";
header += "					    <a class=\"g-btn-3 g-btn-sm toggleCheck\"><span class=\"ion-android-cancel\"><\/span><\/a>";
header += "					<\/div>";
header += "					<div class=\"g-group g-check\">";
header += "					    <a class=\"g-btn-3 g-btn-sm\">Engineering Design and Drafting Technology<\/a>";
header += "					    <a class=\"g-btn-3 g-btn-sm toggleCheck\"><span class=\"ion-android-cancel\"><\/span><\/a>";
header += "					<\/div>";
header += "					<div class=\"g-group g-check\">";
header += "					    <a class=\"g-btn-3 g-btn-sm\">Dental Assisting<\/a>";
header += "					    <a class=\"g-btn-3 g-btn-sm toggleCheck\"><span class=\"ion-android-cancel\"><\/span><\/a>";
header += "					<\/div>";
header += "					<div class=\"g-group g-check\">";
header += "					    <a class=\"g-btn-3 g-btn-sm\">Network Technician<\/a>";
header += "					    <a class=\"g-btn-3 g-btn-sm toggleCheck\"><span class=\"ion-android-cancel\"><\/span><\/a>";
header += "					<\/div>";
header += "			    <\/div>";
header += "		    <\/div>";
header += "		<\/div>";
header += "	<\/div>";
header += "	<header class=\"g-header\">";
header += "		<div class=\"g-container g-clearfix\">";
header += "			<div class=\"logo-sm\">";
header += "				<a href=\"/work/sait\"><img src=\"img\/logo-sm.png\" alt=\"logo\"><\/a>";
header += "			<\/div>";
header += "			<div class=\"logo box-shadow\">";
header += "				<a href=\"/work/sait\"><img src=\"img\/logo.png\" alt=\"logo\"><\/a>";
header += "			<\/div>";
header += "			<div class=\"row secondary-menu-row\">";
header += "				<div class=\"col-1of1\">";
header += "					<ul class=\"secondary-menu\">";
header += "						<li><a class=\"recentlyViewedToggle\"><span class=\"ion-eye g-icon-left\"><\/span>Recently Viewed<\/a><\/li>";
header += "						<li><a class=\"tooltip-login\"><span class=\"ion-locked g-icon-left\"><\/span>Login<span class=\"ion-ios-arrow-down g-icon-right\"><\/span><\/a><\/li>";
header += "";
header += "						<li class=\"search searchToggle\"><a title=\"search\"><span class=\"ion-search\"><\/span><\/a><\/li>";
header += "					<\/ul>";
header += "				<\/div>";
header += "			<\/div>";
header += "			<div class=\"row main-menu-row\">";
header += "				<div class=\"col-1of1\">";
header += "					<div class=\"navToggle\"><a class=\"g-tab-toggle ion-navicon-round\"><\/a><\/div>";
header += "					<ul class=\"main-menu\">";
header += "						<li>";
header += "							<a href=\"programs\">Programs & Courses<\/a>";
header += "							<span class=\"ion-chevron-down mobileNavToggle\"><\/span>";
header += "							<div class=\"mega-menu\">";
header += "								<div class=\"g-container\">";
header += "									<div class=\"row\">";
header += "									    <div class=\"col-1of4 sm-1of2\">";
header += "											<ul class=\"g-primary-list\">";
header += "												<li><a href=\"programs\">View Programs A-Z<\/a><\/li>";
header += "												<li><a href=\"programs?tab=courses\">View Courses A-Z<\/a><\/li>";
header += "												<li><a href=\"continuing-education\">Continuing Education<\/a><\/li>";
header += "												<li><a>Distance Learning<\/a><\/li>";
header += "												<li><a href=\"apprenticeships\">Apprenticeships & Trades<\/a><\/li>";
header += "											<\/ul>";
header += "									    <\/div>";
header += "									    <div class=\"col-1of4 sm-1of2\">";
header += "								        	<div class=\"title\">Other<\/div>";
header += "											<ul class=\"g-secondary-list\">";
header += "												<li><a>Academic Upgrading<\/a><\/li>";
header += "												<li><a>Dual-Credit Programs<\/a><\/li>";
header += "												<li><a>English Language Foundations<\/a><\/li>";
header += "												<li><a>Career Match<span class=\"ion-forward g-icon-right\"><\/span><\/a><\/li>";
header += "											<\/ul>";
header += "									    <\/div>";
header += "									    <div class=\"col-1of4 sm-1of2\">";
header += "								        	<div class=\"title\">Corporate Training<\/div>";
header += "											<ul class=\"g-secondary-list\">";
header += "												<li><a>Search for a Course<\/a><\/li>";
header += "												<li><a>Register Now<\/a><\/li>";
header += "												<li><a>Skills Builder<\/a><\/li>";
header += "												<li><a class=\"all-link\">Overview<span class=\"ion-ios-arrow-forward g-icon-right\"><\/span><\/a><\/li>";
header += "											<\/ul>";
header += "									    <\/div>";
header += "									    <div class=\"col-1of4 sm-1of2\">";
header += "								        	<div class=\"title\">More Offerings<\/div>";
header += "											<ul class=\"g-secondary-list\">";
header += "												<li><a>Culinary Campus<\/a><\/li>";
header += "												<li><a>Summer Camps<\/a><\/li>";
header += "											<\/ul>";
header += "									    <\/div>";
header += "								    <\/div>";
header += "							    <\/div>";
header += "							<\/div>";
header += "						<\/li>";
header += "						<li>";
header += "							<a href=\"admissions\">Admissions<\/a>";
header += "							<span class=\"ion-chevron-down mobileNavToggle\"><\/span>";
header += "							<div class=\"mega-menu\">";
header += "								<div class=\"g-container\">";
header += "									<div class=\"row\">";
header += "										<div class=\"col-1of4 sm-1of2\">";
header += "											<ul class=\"g-primary-list\">";
header += "												<li><a>Admission & Selection<\/a><\/li>";
header += "												<li><a href=\"how-to-apply\">How to Apply<\/a><\/li>";
header += "												<li><a>Transcripts and\/or Documentations<\/a><\/li>";
header += "												<li><a>Testing Services<\/a><\/li>";
header += "												<li><a>After You Apply<\/a><\/li>";
header += "											<\/ul>";
header += "									    <\/div>";
header += "									    <div class=\"col-1of4 sm-1of2\">";
header += "								        	<div class=\"title\">International Students<\/div>";
header += "											<ul class=\"g-secondary-list\">";
header += "												<li><a>International Document Assessment<\/a><\/li>";
header += "												<li><a>International Tuition & Fees<\/a><\/li>";
header += "												<li><a href=\"international-students\" class=\"all-link\">Overview<span class=\"ion-ios-arrow-forward g-icon-right\"><\/span><\/a><\/li>";
header += "											<\/ul>";
header += "									    <\/div>";
header += "									    <div class=\"col-1of4 sm-1of2\">";
header += "								        	<div class=\"title\">Paying for It<\/div>";
header += "											<ul class=\"g-secondary-list\">";
header += "												<li><a>Tuition & Fee Table<\/a><\/li>";
header += "												<li><a>Student Loans<\/a><\/li>";
header += "												<li><a>Student Awards Scholarships<\/a><\/li>";
header += "												<li><a>Grants, Funding & Bursaries<\/a><\/li>";
header += "												<li><a href=\"paying-for-it\" class=\"all-link\">More Financial Information<span class=\"ion-ios-arrow-forward g-icon-right\"><\/span><\/a><\/li>";
header += "											<\/ul>";
header += "									    <\/div>";
header += "									    <div class=\"col-1of4 sm-1of2\">";
header += "								        	<div class=\"title\">Dates & Deadlines<\/div>";
header += "							        		<a class=\"g-event-listing g-sm\">";
header += "												<div class=\"g-date\">";
header += "													<span>Apr<\/span>";
header += "													<span>11<\/span>";
header += "												<\/div>";
header += "												<div class=\"g-info\">";
header += "													Fee payment deadline for new students starting in...";
header += "												<\/div>";
header += "							        		<\/a>";
header += "							        		<a class=\"g-event-listing g-sm\">";
header += "												<div class=\"g-date\">";
header += "													<span>Apr<\/span>";
header += "													<span>15<\/span>";
header += "												<\/div>";
header += "												<div class=\"g-info\">";
header += "													Fee payment deadline for new students starting in...";
header += "												<\/div>";
header += "							        		<\/a>";
header += "											<ul class=\"g-secondary-list\">";
header += "												<li><a class=\"all-link\">View All<span class=\"ion-ios-arrow-forward g-icon-right\"><\/span><\/a><\/li>";
header += "											<\/ul>";
header += "									    <\/div>";
header += "								    <\/div>";
header += "							    <\/div>";
header += "							<\/div>";
header += "						<\/li>";
header += "						<li>";
header += "							<a href=\"student-resources\">Student Resources<\/a>";
header += "							<span class=\"ion-chevron-down mobileNavToggle\"><\/span>";
header += "							<div class=\"mega-menu\">";
header += "								<div class=\"g-container\">";
header += "									<div class=\"row\">";
header += "										<div class=\"col-1of4 sm-1of2\">";
header += "								        	<div class=\"title\">Academic Services<\/div>";
header += "											<ul class=\"g-secondary-list\">";
header += "												<li><a>Learning Skills Services<\/a><\/li>";
header += "												<li><a>Prior Learning Assessment & Recognition<\/a><\/li>";
header += "												<li><a>Library<span class=\"ion-forward g-icon-right\"><\/span><\/a><\/li>";
header += "												<li><a>Accessibility<\/a><\/li>";
header += "												<li><a class=\"all-link\">View All<span class=\"ion-ios-arrow-forward g-icon-right\"><\/span><\/a><\/li>";
header += "											<\/ul>";
header += "									    <\/div>";
header += "									    <div class=\"col-1of4 sm-1of2\">";
header += "								        	<div class=\"title\">Health, Wellness & Security<\/div>";
header += "											<ul class=\"g-secondary-list\">";
header += "												<li><a>Student Health & Dental<\/a><\/li>";
header += "												<li><a>Student Development Counselling<\/a><\/li>";
header += "												<li><a>Safewalk<\/a><\/li>";
header += "												<li><a>Campus Security<\/a><\/li>";
header += "												<li><a class=\"all-link\">View All<span class=\"ion-ios-arrow-forward g-icon-right\"><\/span><\/a><\/li>";
header += "											<\/ul>";
header += "									    <\/div>";
header += "									    <div class=\"col-1of4 sm-1of2\">";
header += "								        	<div class=\"title\">Student Life<\/div>";
header += "											<ul class=\"g-secondary-list\">";
header += "												<li><a>SAIT Recreation<\/a><\/li>";
header += "												<li><a>SAIT Bookstore<\/a><\/li>";
header += "												<li><a>Food Services<\/a><\/li>";
header += "												<li><a>Housing<\/a><\/li>";
header += "												<li><a class=\"all-link\">View All<span class=\"ion-ios-arrow-forward g-icon-right\"><\/span><\/a><\/li>";
header += "											<\/ul>";
header += "									    <\/div>";
header += "									    <div class=\"col-1of4 sm-1of2\">";
header += "								        	<div class=\"title\">Services for Students<\/div>";
header += "											<ul class=\"g-secondary-list\">";
header += "												<li><a>Helpline<\/a><\/li>";
header += "												<li><a>Computers, Network Access & Technical Support<\/a><\/li>";
header += "												<li><a>Transcripts & Credentials<\/a><\/li>";
header += "												<li><a>Student Employment Services<\/a><\/li>";
header += "												<li><a href=\"services-for-students\" class=\"all-link\">View All<span class=\"ion-ios-arrow-forward g-icon-right\"><\/span><\/a><\/li>";
header += "											<\/ul>";
header += "									    <\/div>";
header += "								    <\/div>";
header += "							    <\/div>";
header += "							<\/div>";
header += "						<\/li>";
header += "						<li>";
header += "							<a href=\"about-sait\">About SAIT<\/a>";
header += "							<span class=\"ion-chevron-down mobileNavToggle\"><\/span>";
header += "							<div class=\"mega-menu\">";
header += "								<div class=\"g-container\">";
header += "									<div class=\"row\">";
header += "										<div class=\"col-1of4 sm-1of2\">";
header += "								        	<div class=\"title\">Campus<\/div>";
header += "											<ul class=\"g-secondary-list\">";
header += "												<li><a href=\"campus-map\">Campus Map<\/a><\/li>";
header += "												<li><a>Parking Rates & Transportation<\/a><\/li>";
header += "												<li><a>Campus Security<\/a><\/li>";
header += "												<li><a href=\"contact-us\">Contact Us<\/a><\/li>";
header += "												<li><a href=\"campus\" class=\"all-link\">SAIT Campus<span class=\"ion-ios-arrow-forward g-icon-right\"><\/span><\/a><\/li>";
header += "											<\/ul>";
header += "									    <\/div>";
header += "									    <div class=\"col-1of4 sm-1of2\">";
header += "								        	<div class=\"title\">Who We Are<\/div>";
header += "											<ul class=\"g-secondary-list\">";
header += "												<li><a>History of SAIT<\/a><\/li>";
header += "												<li><a>Schools<\/a><\/li>";
header += "												<li><a>Research & Innovation<\/a><\/li>";
header += "												<li><a href=\"news-and-events\">News & Events<\/a><\/li>";
header += "												<li><a href=\"media-centre\">Media Centre<\/a><\/li>";
header += "												<li><a href=\"work-at-sait\">Work at SAIT<\/a><\/li>";
header += "											<\/ul>";
header += "									    <\/div>";
header += "									    <div class=\"col-1of4 sm-1of2\">";
header += "								        	<div class=\"title\">Administration<\/div>";
header += "											<ul class=\"g-secondary-list\">";
header += "												<li><a>Awards<\/a><\/li>";
header += "												<li><a>Departments<\/a><\/li>";
header += "												<li><a>Governance<\/a><\/li>";
header += "												<li><a>Policies & Procedures<\/a><\/li>";
header += "												<li><a class=\"all-link\">View All<span class=\"ion-ios-arrow-forward g-icon-right\"><\/span><\/a><\/li>";
header += "											<\/ul>";
header += "									    <\/div>";
header += "									    <div class=\"col-1of4 sm-1of2\">";
header += "								        	<div class=\"title\">Events<\/div>";
header += "								        	<a class=\"g-event-listing g-sm\">";
header += "												<div class=\"g-date\">";
header += "													<span>Apr<\/span>";
header += "													<span>01<\/span>";
header += "												<\/div>";
header += "												<div class=\"g-info\">";
header += "													Free Info Session: Chemical Engineering Technology";
header += "												<\/div>";
header += "							        		<\/a>";
header += "							        		<a class=\"g-event-listing g-sm\">";
header += "												<div class=\"g-date\">";
header += "													<span>Apr<\/span>";
header += "													<span>02<\/span>";
header += "												<\/div>";
header += "												<div class=\"g-info\">";
header += "													Info Session: Energy Asset Management";
header += "												<\/div>";
header += "							        		<\/a>";
header += "											<ul class=\"g-secondary-list\">";
header += "												<li><a href=\"events\" class=\"all-link\">View All<span class=\"ion-ios-arrow-forward g-icon-right\"><\/span><\/a><\/li>";
header += "											<\/ul>";
header += "									    <\/div>";
header += "								    <\/div>";
header += "							    <\/div>";
header += "							<\/div>";
header += "						<\/li>";
header += "						<li>";
header += "							<a href=\"alumni\">Alumni<\/a>";
header += "							<span class=\"ion-chevron-down mobileNavToggle\"><\/span>";
header += "							<div class=\"mega-menu\">";
header += "								<div class=\"g-container\">";
header += "									<div class=\"row\">";
header += "										<div class=\"col-1of4 g-empty\">";
header += "";
header += "										<\/div>";
header += "										<div class=\"col-1of4 sm-1of2\">";
header += "											<ul class=\"g-primary-list\">";
header += "												<li><a href=\"news\">Alumni News<\/a><\/li>";
header += "												<li><a>Distinguished & Outstanding Alumni<\/a><\/li>";
header += "												<li><a>Alumni Perks<\/a><\/li>";
header += "												<li><a>Student Awards<\/a><\/li>";
header += "												<li><a>Stay Connected<\/a><\/li>";
header += "											<\/ul>";
header += "									    <\/div>";
header += "									    <div class=\"col-1of4 sm-1of2\">";
header += "								        	<div class=\"title\">Donors<\/div>";
header += "											<ul class=\"g-secondary-list\">";
header += "												<li><a>Donate to SAIT<\/a><\/li>";
header += "												<li><a>Gifts at Work<\/a><\/li>";
header += "												<li><a>Giving Clubs<\/a><\/li>";
header += "												<li><a>Reports to Donors<\/a><\/li>";
header += "												<li><a>FAQs<\/a><\/li>";
header += "												<li><a href=\"donors\" class=\"all-link\">View All<span class=\"ion-ios-arrow-forward g-icon-right\"><\/span><\/a><\/li>";
header += "											<\/ul>";
header += "									    <\/div>";
header += "									    <div class=\"col-1of4 sm-1of2\">";
header += "								        	<div class=\"title\">Alumni Events<\/div>";
header += "								        	<a class=\"g-event-listing g-sm\">";
header += "												<div class=\"g-date\">";
header += "													<span>Apr<\/span>";
header += "													<span>04<\/span>";
header += "												<\/div>";
header += "												<div class=\"g-info\">";
header += "													Free Info Session: Chemical Engineering Technology";
header += "												<\/div>";
header += "							        		<\/a>";
header += "							        		<a class=\"g-event-listing g-sm\">";
header += "												<div class=\"g-date\">";
header += "													<span>Apr<\/span>";
header += "													<span>22<\/span>";
header += "												<\/div>";
header += "												<div class=\"g-info\">";
header += "													Info Session: Energy Asset Management";
header += "												<\/div>";
header += "							        		<\/a>";
header += "											<ul class=\"g-secondary-list\">";
header += "												<li><a class=\"all-link\">View All<span class=\"ion-ios-arrow-forward g-icon-right\"><\/span><\/a><\/li>";
header += "											<\/ul>";
header += "									    <\/div>";
header += "								    <\/div>";
header += "							    <\/div>";
header += "							<\/div>";
header += "						<\/li>";
header += "					<\/ul>";
header += "				<\/div>";
header += "			<\/div>";
header += "		<\/div>";
header += "	<\/header>";
header += "<\/div>";

document.write(header);